seg 26 dez 2022 01:46:59 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/void-install b/void-install
--- a/void-install
+++ b/void-install
@@ -2,10 +2,10 @@
 
 #  void-install
 #  Created: 2022/12/24
-#  Altered: 2022/12/25
+#  Altered: 2022/12/26
 #
 #  Copyright (c) 2022-2022, Vilmar Catafesta <vcatafesta@gmail.com>
-#                2022-2022, Felipe Nogueira <fnogueira@gmail.com>
+#                2022-2022, Felipe Nogueira <contato.fnog@gmail.com>
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -34,21 +34,40 @@
 
 #system
 APP="${0##*/}"
-_VERSION_='1.0.20221225'
-readonly DEPENDENCIES=(tar wget sed cat chroot tput printf blkid fdisk mkfs.ext4 mkfs.ext2)
+_VERSION_='1.1.20221226'
+readonly DEPENDENCIES=(tar wget sed cat chroot tput printf blkid fdisk mkfs.ext4 mkfs.ext2 dialog sfdisk lsblk)
+declare -A AsUser
 
 sh_ambiente() {
-	export LC_ALL=C
-	export LANG=C
+	#export LC_ALL=C
+	#export LANG=C
 	readonly dir_install='/mnt/voidlinux'
 	readonly app_conf='void-install.conf'
 	readonly BOOTLOG='/tmp/void-install.log'
 	readonly URL_GOOGLE='https://google.com'
 	readonly url_mirror='http://void.chililinux.com/voidlinux'
+	readonly cmsgusermanager="$APP v$_VERSION_ configuracao"
+	readonly ccreatenewuser='Configurações'
+	readonly cmsgadduser='Aguarde, criando usuario'
+	readonly cdisco='DISCO'
+ 	readonly cchoosedisk='Escolha o disco:'
+	readonly cmsg_part_disk='Visualizar partições do disco'
+   readonly buttonOK='Accept'
+   readonly buttonCancel='Cancel'
+	readonly buttonback='Finalizar'
+   readonly buttonpart='Info disco'
 	readonly grafico=0
 	readonly true=1
 	readonly false=0
 	: "${ccabec="$APP ${_VERSION_}"}"
+	: "${DIALOG=${DIALOG:-"dialog"}}"
+	# flag dialog exit status codes
+   : "${D_OK=0}"
+   : "${D_CANCEL=1}"
+   : "${D_HELP=2}"
+   : "${D_EXTRA=3}"
+   : "${D_ITEM_HELP=4}"
+   : "${D_ESC=255}"
 	: echo "$tarball"
 
 	if [ -z "${COLUMNS}" ]; then
@@ -64,7 +83,7 @@ sh_ambiente() {
 }
 
 sh_touchconf(){
-   cat > "$app_conf" <<-'_EOF_'
+   cat > "$app_conf" <<- EOF
 ######################################################################
 # void-install.conf
 # Gerado por void-install
@@ -84,7 +103,7 @@ _KEYMAP="br-abnt2"
 _CLOCK="UTC"
 _PKGS="vim"
 #end
-_EOF_
+EOF
 }
 
 sh_config() {
@@ -93,6 +112,15 @@ sh_config() {
 	if 	[[ -f "$app_conf" ]]
 	then 	source "$app_conf"
 	else  die "ERRO: falha na abertura de $app_conf!"
+	fi
+	sh_setadduser
+}
+
+sh_ascii_lines() {
+	if [[ "$LANG" =~ 'UTF-8' ]]; then
+		export NCURSES_NO_UTF8_ACS=0
+	else
+		export NCURSES_NO_UTF8_ACS=1
 	fi
 }
 
@@ -275,12 +303,24 @@ die() {
    exit 1
 }
 
-conf()
+readconf()
 {
    read -r -p "$1 [Y/n]"
    [[ ${REPLY^} == "" ]] && return $false
    [[ ${REPLY^} == N ]]  && return $true || return $false
 }
+
+conf() {
+   ${DIALOG}                     \
+      --title     "$1"           \
+      --backtitle "$ccabec"      \
+      --yes-label "$yeslabel"    \
+      --no-label  "$nolabel"     \
+      --yesno     "$2"           \
+      10 100
+   return $?
+}
+
 
 sh_testdisk(){
 	local result=0
@@ -302,7 +342,7 @@ sh_mkparted(){
 	replicate "=" "$COLUMNS"
 	echo "${red}AVISO, CUIDADO, tudo será apagado!!${reset}"
 	replicate "=" "$COLUMNS"
-	if conf "Continuar com o particionamento em ${_DEVICE} ?" ; then
+	if readconf "Continuar com o particionamento em ${_DEVICE} ?" ; then
 		msg "INFO" "$(log_info_msg "Criando partições em ${_DEVICE}")"
 	   parted --script "$_DEVICE" --                                   		\
 	      mklabel gpt                                                       \
@@ -319,33 +359,33 @@ sh_mkparted(){
 
 sh_update_mirror() {
 	msg "INFO" "$(log_info_msg "Atualizando mirror em $dir_install")"
-	cat > "$dir_install/etc/xbps.d/00-reposytory-main.conf" <<-'_EOF_'
-repository="$url_mirror"/current
-repository="$url_mirror"/current/nonfree
-repository="$url_mirror"/current/multilib
-repository="$url_mirror"/current/multilib/nonfree
-_EOF_
+	cat > "$dir_install/etc/xbps.d/00-reposytory-main.conf" <<- EOF
+repository=$url_mirror/current
+repository=$url_mirror/current/nonfree
+repository=$url_mirror/current/multilib
+repository=$url_mirror/current/multilib/nonfree
+EOF
 	evaluate_retval "$?"
 }
 
 sh_update_rc() {
 	msg "INFO" "$(log_info_msg "Ajustando rc.local em $dir_install")"
-	cat > "$dir_install/etc/rc.local" <<-'_EOF_'
+	cat > "$dir_install"/etc/rc.local <<- EOF
 HOSTNAME="${_HOSTNAME}"
 HARDWARECLOCK="${_CLOCK}"
 TIMEZONE="${_TIMEZONE}"
 KEYMAP="${_KEYMAP}"
-_EOF_
+EOF
 	evaluate_retval "$?"
 }
 
 sh_update_locale() {
 	msg "INFO" "$(log_info_msg "Ajustando locale.conf em $dir_install")"
-	cat > "$dir_install/etc/locale.conf" <<-'_EOF_'
+	cat > "$dir_install/etc/locale.conf" <<- EOF
 LANG=en_US.UTF-8
 LC_COLLATE=C
 LC_ALL=en_US.UTF-8
-_EOF_
+EOF
 	evaluate_retval "$?"
 }
 
@@ -358,7 +398,29 @@ sh_update_hostname() {
 sh_update_timezone() {
 	msg "INFO" "$(log_info_msg "Ajustando timezone em $dir_install")"
 	sed -e "/en_US.UTF-8 UTF-8/s/^\#//" -i "$dir_install/etc/default/libc-locales"
-	ln -s "$dir_install/usr/share/zoneinfo/${_TIMEZONE}" "$dir_install/etc/localtime"
+	sed -e "/pt_BR.UTF-8 UTF-8/s/^\#//" -i "$dir_install/etc/default/libc-locales"
+	ln -sf "$dir_install/usr/share/zoneinfo/${_TIMEZONE}" "$dir_install/etc/localtime"
+	evaluate_retval "$?"
+}
+
+sh_set_keymap(){
+	msg "INFO" "$(log_info_msg "Ajustando teclado em $dir_install")"
+   [[ ! -e $dir_install/etc/vconsole.conf  ]] && >| $dir_install/etc/vconsole.conf
+	if [[ -f $dir_install/etc/vconsole.conf ]]; then
+		echo "KEYMAP=$_KEYMAP" >> $dir_install/etc/vconsole.conf
+		sed -i -e "s|KEYMAP=.*|KEYMAP=$_KEYMAP|g" $dir_install/etc/vconsole.conf
+	else
+		sed -i -e "s|#\?KEYMAP=.*|KEYMAP=$_KEYMAP|g" $dir_install/etc/rc.conf
+	fi
+	evaluate_retval "$?"
+}
+
+sh_update_bashrc(){
+	msg "INFO" "$(log_info_msg "Ajustando bashrc em $dir_install")"
+   [[ ! -e $dir_install/etc/bash/bashrc.d/bashrc.sh ]] && >| $dir_install/etc/bash/bashrc.d/bashrc.sh
+	if [[ -f $dir_install/etc/bash/bashrc.d/bashrc.sh ]]; then
+		echo "PS1='\e[32;1m\u \e[33;1m→ \e[36;1m\h \e[37;0m\w\n\e[35;1m�# \e[m'" >> $dir_install/etc/bash/bashrc.d/bashrc.sh
+	fi
 	evaluate_retval "$?"
 }
 
@@ -386,20 +448,31 @@ sh_bind() {
 }
 
 sh_mkuser() {
-	msg "INFO" "$(log_info_msg "Ajustando root passwd em $dir_install")"
-	echo -e "${_PASSWD_ROOT}\n${_PASSWD_ROOT}" | chroot $dir_install passwd root > /dev/null 2>&1
-	evaluate_retval "$?"
-#	chroot "$dir_install" useradd -N -p "$(openssl passwd -1 "{$_PASSWD_USER}")" "${_USER}" > /dev/null 2>&1
-#	chroot "$dir_install" usermod -G wheel,audio,users "${_USER}" > /dev/null 2>&1
-	msg "INFO" "$(log_info_msg "Criando usuario $_USER e ajustando passwd em $dir_install")"
-	chroot "$dir_install" /bin/bash -c "useradd -m ${_USER} -G audio,video,wheel,xbuilder -p ${_PASSWD_USER} > /dev/null 2>&1"
-	chroot "$dir_install" /bin/bash -c "(echo ${_USER}:${_PASSWD_USER}) | chpasswd -m > /dev/null 2>&1"
-	evaluate_retval "$?"
+	#	msg "INFO" "$(log_info_msg "Ajustando root passwd em $dir_install")"
+	#	echo -e "${_PASSWD_ROOT}\n${_PASSWD_ROOT}" | chroot $dir_install passwd root > /dev/null 2>&1
+	#	evaluate_retval "$?"
+	#	msg "INFO" "$(log_info_msg "Criando usuario $_USER e ajustando passwd em $dir_install")"
+	#	chroot "$dir_install" /bin/bash -c "useradd -m ${_USER} -G audio,video,wheel,xbuilder -p ${_PASSWD_USER} > /dev/null 2>&1"
+	#	chroot "$dir_install" /bin/bash -c "(echo ${_USER}:${_PASSWD_USER}) | chpasswd -m > /dev/null 2>&1"
+	#	evaluate_retval "$?"
+
+   if [[ -n "${AsUser[cpassroot]}" ]]; then
+      msg "INFO" "$(log_info_msg "$cmsgadduser: root")"
+      chroot "$dir_install" /bin/bash -c "(echo root:${AsUser[cpassroot]}) | chpasswd -m > /dev/null 2>&1"
+		evaluate_retval "$?"
+   fi
+
+	if [[ -n "${AsUser[cuser]}" ]]; then
+		msg "INFO" "$(log_info_msg "$cmsgadduser: ${AsUser[cuser]} - ${AsUser[cfullname]} ")"
+		chroot "$dir_install" /bin/bash -c "useradd -m ${AsUser[cuser]} -G ${AsUser[cgroups]} -p ${AsUser[cpass]} -c "${AsUser[cfullname]}" > /dev/null 2>&1"
+		chroot "$dir_install" /bin/bash -c "(echo ${AsUser[cuser]}:${AsUser[cpass]}) | chpasswd -m > /dev/null 2>&1"
+		evaluate_retval "$?"
+   fi
 }
 
 sh_mkfstab() {
 	msg "INFO" "$(log_info_msg "Criando fstab em $dir_install")"
-cat << EOF > "$dir_install/etc/fstab"
+cat > "$dir_install/etc/fstab" <<- EOF
 UUID=$(blkid -o value -s UUID "${_PART_BOOT}") /boot	ext2 defaults 0 2
 UUID=$(blkid -o value -s UUID "${_PART_ROOT}") / 		ext4 defaults 0 1
 EOF
@@ -447,6 +520,8 @@ sh_mount() {
 }
 
 sh_install() {
+	local apkgs=(base-system xz lvm2 wireless_tools mkinitcpio mkinitcpio-udev nano grub efivar efibootmgr os-prober)
+
 	sh_umountfs
 	if ! sh_mkparted; then die "Erro"; fi
 	if ! sh_mkfs 	 ; then die "Erro"; fi
@@ -457,48 +532,74 @@ sh_install() {
 	if tar xpf "$_TARBALL_ROOTFS" --xattrs-include='*.*' --numeric-owner -C $dir_install > /dev/null 2>&1; then
 		evaluate_retval "$?"
 		sh_bind
+
 		msg "INFO" "$(log_info_msg "Ajustando /etc/resolv.conf em $dir_install")"
 		cp /etc/resolv.conf "$dir_install/etc/" > /dev/null 2>&1
 		evaluate_retval "$?"
+
 		sh_update_mirror
+
 		msg "INFO" "$(log_info_msg "Atualizando repositorio em $dir_install")"
 		chroot "$dir_install" /bin/bash -c "xbps-install -Suy xbps" > /dev/null 2>&1
 		evaluate_retval "$?"
+
 		msg "INFO" "$(log_info_msg "Atualizando sistema em $dir_install")"
 		chroot "$dir_install" /bin/bash -c "xbps-install -uy" > /dev/null 2>&1
 		evaluate_retval "$?"
-		msg "INFO" "$(log_info_msg "Instalando pacotes adicionais em $dir_install")"
-		chroot "$dir_install" /bin/bash -c "xbps-install -y base-system base-minimal tar xz kmod" > /dev/null 2>&1
-		chroot "$dir_install" /bin/bash -c "xbps-install -y e2fsprogs dosfstools lvm2 sudo iproute2 iputils" > /dev/null 2>&1
-		chroot "$dir_install" /bin/bash -c "xbps-install -y dhcpcd wpa_supplicant wireless_tools iw kbd mdocml" > /dev/null 2>&1
-		chroot "$dir_install" /bin/bash -c "xbps-install -y man-pages vim nano grub efivar efibootmgr os-prober" > /dev/null 2>&1
-		chroot "$dir_install" /bin/bash -c "xbps-install -y mkinitcpio mkinitcpio-udev" > /dev/null 2>&1
+
+		#msg "INFO" "$(log_info_msg "Instalando pacotes adicionais $pkg em $dir_install")"
+		#chroot "$dir_install" /bin/bash -c "xbps-install -y base-system base-minimal tar xz kmod" > /dev/null 2>&1
+		#chroot "$dir_install" /bin/bash -c "xbps-install -y e2fsprogs dosfstools lvm2 sudo iproute2 iputils" > /dev/null 2>&1
+		#chroot "$dir_install" /bin/bash -c "xbps-install -y dhcpcd wpa_supplicant wireless_tools iw kbd mdocml" > /dev/null 2>&1
+		#chroot "$dir_install" /bin/bash -c "xbps-install -y man-pages vim nano grub efivar efibootmgr os-prober" > /dev/null 2>&1
+		#chroot "$dir_install" /bin/bash -c "xbps-install -y mkinitcpio mkinitcpio-udev" > /dev/null 2>&1
+		#evaluate_retval "$?"
+
+		for pkg in "${apkgs[@]}"
+		do
+			msg "INFO" "$(log_info_msg "Instalando $pkg em $dir_install")"
+			chroot "$dir_install" /bin/bash -c "xbps-install -y $pkg" > /dev/null 2>&1
+			evaluate_retval "$?"
+		done
+
+		msg "INFO" "$(log_info_msg "Instalando pacotes adicionais $pkg em $dir_install")"
 		chroot "$dir_install" /bin/bash -c "xbps-install -y $_PKGS" > /dev/null 2>&1
 		evaluate_retval "$?"
-		msg "INFO" "$(log_info_msg "Instalando kernel em $dir_install")"
-		chroot "$dir_install" /bin/bash -c "xbps-install -y linux linux-headers" > /dev/null 2>&1
-		evaluate_retval "$?"
+
+#		msg "INFO" "$(log_info_msg "Instalando kernel em $dir_install")"
+#		chroot "$dir_install" /bin/bash -c "xbps-install -y linux linux-headers" > /dev/null 2>&1
+#		evaluate_retval "$?"
+
 		msg "INFO" "$(log_info_msg "Instalando grub no $_DEVICE")"
 		chroot "$dir_install" /bin/bash -c "grub-install $_DEVICE" > /dev/null 2>&1
 		evaluate_retval "$?"
+
 		msg "INFO" "$(log_info_msg "Gerando grub.cfg em $dir_install")"
 		chroot "$dir_install" /bin/bash -c "grub-mkconfig -o /boot/grub/grub.cfg" > /dev/null 2>&1
 		evaluate_retval "$?"
+
 		msg "INFO" "$(log_info_msg "Removendo pacote bootstrap em $dir_install")"
 		chroot "$dir_install" /bin/bash -c "xbps-remove -y base-voidstrap" > /dev/null 2>&1
 		evaluate_retval "$?"
+
 		sh_update_hostname
 		sh_update_rc
 		sh_update_timezone
+
 		msg "INFO" "$(log_info_msg "Reconfigurando locales em $dir_install")"
 		chroot "$dir_install" /bin/bash -c "xbps-reconfigure -f glibc-locales" > /dev/null 2>&1
 		evaluate_retval "$?"
+
 		sh_update_locale
 		sh_mkuser
 		sh_mkfstab
+		sh_set_keymap
+		sh_update_bashrc
+
 		msg "INFO" "$(log_info_msg "Certificando que todos pacotes estejam configurados corretamente em $dir_install")"
 		chroot "$dir_install" /bin/bash -c "xbps-reconfigure -fa" > /dev/null 2>&1
 		evaluate_retval "$?"
+
 		sh_mkservice
 	else
 		evaluate_retval "$?"
@@ -507,7 +608,239 @@ sh_install() {
 	sh_umountfs
 }
 
+sh_backup_partitions() {
+	if [ $# -ge 2 ]; then
+		local disk="${1}"
+		local device="${2}"
+		local cdatetime=$(sh_diahora)
+		local tmpdir="/tmp/$_APP_"
+		local filetmp="$tmpdir/${device}.$cdatetime.dump"
+
+		mkdir -p $tmpdir 2> /dev/null
+		sfdisk -d $disk > $filetmp 2> /dev/null
+		#  alerta "BACKUP DA TABELA DE PARTICOES"    \
+		#         "Dispositivo : $disk"              \
+		#         "  Backup on : ${filetmp}"         \
+		#        "$(replicate "=" 80)"               \
+		#         "$(cat $filetmp)"
+	fi
+}
+
+sh_diahora() {
+	DIAHORA=`date +"%d%m%Y-%T" | sed 's/://g'`
+	printf "%s\n" $DIAHORA
+}
+
+now() {
+	printf "%(%m-%d-%Y %H:%M:%S)T\n" $(date +%s)
+}
+
+sh_setadduser()
+{
+   # usuario/senha/hostmame/group
+   AsUser[cfullname]=""
+   AsUser[cuser]="$_USER"
+   AsUser[cpass]="$_PASSWD_USER"
+   AsUser[cpassroot]="$_PASSWD_ROOT"
+   AsUser[chostname]="$_HOSTNAME"
+   AsUser[cgroups]="audio,video,wheel,xbuilder"
+}
+
+sh_disk_info() {
+	unset ARRAY_DSK_{DISKS,DEVICES,SIZE,TRAN,MODEL,LABEL,SERIAL}
+	local {NAME,PATH,SIZE,TRAN,MODEL,LABEL,SERIAL}_
+	while read line
+	do
+		eval "${line//=/_=}"
+#     [[ -z "$TRAN_" ]] && continue
+      ARRAY_DSK_DISKS+=( $NAME_ )
+    ARRAY_DSK_DEVICES+=( $PATH_ )
+       ARRAY_DSK_SIZE+=( $SIZE_ )
+#      ARRAY_DSK_TRAN+=( ${TRAN_:-loop} )
+       ARRAY_DSK_TRAN+=( ${TRAN_:-${TYPE_}} )
+      ARRAY_DSK_MODEL+=( "${MODEL_:-unknown}" )
+      ARRAY_DSK_LABEL+=( "${LABEL_:-""}" )
+      ARRAY_DSK_SERIAL+=( "${SERIAL_:-""}" )
+	done < <(lsblk -PAo TYPE,NAME,PATH,SIZE,TRAN,MODEL,LABEL,SERIAL | grep -P 'TYPE="(disk|loop|lvm)"' | sort -k5,5 -k2,2)
+}
+
+sh_choosedisk() {
+	while true
+	do
+		sh_disk_info
+    	LDISK=$false
+		local xmsg="$cdisco"
+		local array=()
+		local i
+		local n=0
+		local nc=0
+		local result
+		#local sep="\xe2\x94\x82"
+		local sep=" | "
+
+		for i in "${ARRAY_DSK_DEVICES[@]}"
+		do
+         array[((n++))]="$i"
+         array[((n++))]=$(printf "%-6s$sep%6s$sep%-30s" "${ARRAY_DSK_TRAN[$nc]}" "${ARRAY_DSK_SIZE[$nc]}" "${ARRAY_DSK_MODEL[$nc]}")
+			((nc++))
+		done
+
+    	sd=$(${DIALOG}  																				\
+    				--title 			"$xmsg"								  							\
+    				--backtitle	 	"$ccabec"				 										\
+    				--cancel-label "$buttonback"													\
+    				--colors																				\
+	            --extra-button                                                    \
+               --extra-label  "$buttonpart"                                      \
+    				--menu 			"\n$cchoosedisk" 0 0 10 "${array[@]}" 2>&1 >/dev/tty 	)
+
+    	exit_status=$?
+		case $exit_status in
+    	"$D_ESC"|"$D_CANCEL")
+			"$DIALOG" --clear --backtitle "$backtitle" --yesno "Deseja sair sem instalar?" 0 0
+			case $? in
+	      	"$D_OK")
+					die "Finalizando..."
+             	break
+	            ;;
+				"$D_CANCEL")
+					exit_status=99
+					continue
+					;;
+			esac
+    		;;
+		3)
+      	result=$(fdisk -l "$sd");
+         display_result "$result" "$cmsg013" "$cmsg_part_disk"
+         continue
+         ;;
+		esac
+
+    	if [[ -n "$sd" ]]; then
+			{	local item
+            index=0
+            for item in "${ARRAY_DSK_DEVICES[@]}"
+            do
+            	[[ "$item" = "$sd" ]] && { break; }
+               ((index++))
+            done
+			}
+			DEVICE_ORIGEM="${ARRAY_DSK_DISKS[index]}"
+			_DEVICE="/dev/$DEVICE_ORIGEM"
+			MODEL_ORIGEM="${ARRAY_DSK_MODEL[index]}"
+			SIZE_ORIGEM="${ARRAY_DSK_SIZE[index]}"
+			TRAN_ORIGEM="${ARRAY_DSK_TRAN[index]}"
+			sh_backup_partitions "${sd}" "${DEVICE_ORIGEM}"
+			return 0
+		fi
+    	break
+	done
+}
+
+display_result() {
+	local xbacktitle=$ccabec
+	if [[ "$3" != "" ]] ; then
+		xbacktitle="$3"
+	fi
+	${DIALOG}   --title  "$2"              \
+               --beep                     \
+               --no-collapse              \
+               --no-cr-wrap               \
+               --backtitle "$xbacktitle"  \
+               --msgbox    "$1"           \
+               00 0
+}
+
+sh_confadduser()
+{
+   while true
+   do
+      exec 3>&1
+         usertext=$(${DIALOG}                         \
+         --backtitle       "$cmsgusermanager"         \
+         --insecure        "$@"                       \
+         --mixedform       "$ccreatenewuser"          \
+         14 50 0                                      \
+         "Nome Completo : " 1 1 "${AsUser[cfullname]}"    1 17 40 0 0 \
+         "Username      : " 2 1 "${AsUser[cuser]}"        2 17 20 0 0 \
+         "Password user : " 3 1 "${AsUser[cpass]}"        3 17 20 0 1 \
+         "Password root : " 4 1 "${AsUser[cpassroot]}"    4 17 20 0 1 \
+         "Hostname      : " 5 1 "${AsUser[chostname]}"    5 17 20 0 0 \
+         "Disco destino : " 6 1 "${_DEVICE}"              6 17 20 0 2 \
+         "Tam/Modelo    : " 7 1 "${SIZE_ORIGEM}/${MODEL_ORIGEM}"        7 17 20 0 2 \
+         2>&1 1>&3)
+         exit_status=$?
+
+         case $exit_status in
+            "$D_ESC"|"$D_CANCEL")
+		         "$DIALOG" --clear --backtitle "$backtitle" --yesno "Deseja sair sem instalar?" 0 0
+		         case $? in
+		            "$D_OK")
+		               die "Finalizando..."
+		               break
+		               ;;
+		            "$D_CANCEL")
+		               exit_status=99
+							continue
+		               ;;
+		         esac
+		         ;;
+            "$D_OK")
+               mapfile -t <<< "$usertext" aUser
+               AsUser[cfullname]="${aUser[0]}"
+               AsUser[cuser]="${aUser[1]}"
+               AsUser[cpass]="${aUser[2]}"
+               AsUser[cpassroot]="${aUser[3]}"
+               AsUser[chostname]="${aUser[4]}"
+               _HOSTNAME="${aUser[4]}"
+
+               if [[ "${AsUser[cuser]}" == "root" ]]; then
+                  if ! conf "*** USER ***" "\nUsuario não pode ser root! Novamente?"; then
+                     die "*** USER *** " "Cadastro de usuario cancelado"
+                     return 1
+                  fi
+                  sh_confadduser
+               fi
+
+               if [[ -z "${AsUser[cuser]}" ]]; then
+                  if ! conf "*** USER ***" "\nUsuario não pode ser vazio! Novamente?"; then
+                     die "*** USER *** " "Cadastro de usuario cancelado"
+                     return 1
+                  fi
+                  sh_confadduser
+               fi
+
+               if [[ -z "${AsUser[cpass]}" ]]; then
+                  if ! conf "*** USER ***" "\nSenha do usuario não pode ser vazia! Novamente?"; then
+                     die "*** USER *** " "Cadastro de usuario cancelado"
+                     return 1
+                 fi
+                  sh_confadduser
+               fi
+               log_info_msg 'Configurações efetuadas. Prosseguindo com instalação.'
+					evaluate_retval "$?"
+               ;;
+         esac
+      exec 3>&-
+      return 0
+   done
+}
+
+sh_dryrun(){
+	sh_umountfs
+	sh_mount
+	sh_bind
+	sh_update_rc
+	sh_update_mirror
+	sh_update_timezone
+	sh_set_keymap
+	sh_update_bashrc
+	chroot "$dir_install" /bin/bash
+	sh_umountfs
+}
+
 sh_ambiente
+sh_ascii_lines
 setvarcolors
 log_prefix
 msg "INFO" "$(log_info_msg "Configurando ambiente")"
@@ -519,4 +852,7 @@ sh_config
 evaluate_retval "$?"
 sh_checknet "$URL_GOOGLE" || return 1
 sh_checktarball
+sh_choosedisk
+sh_confadduser
+#sh_dryrun
 sh_install
