sex 30 dez 2022 01:45:21 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/void-install b/void-install
--- a/void-install
+++ b/void-install
@@ -3,7 +3,7 @@
 
 #  void-install
 #  Created: 2022/12/24
-#  Altered: 2022/12/28
+#  Altered: 2022/12/30
 #
 #  Copyright (c) 2022-2022, Vilmar Catafesta <vcatafesta@gmail.com>
 #                2022-2022, Felipe Nogueira <contato.fnog@gmail.com>
@@ -35,7 +35,7 @@
 
 #system
 APP="${0##*/}"
-_VERSION_='0.95.20221228'
+_VERSION_='1.05.20221230'
 readonly DEPENDENCIES=(tar wget sed cat grep chroot tput printf blkid fdisk mkfs.ext4 mkfs.ext2 mkfs.btrfs mkfs.xfs dialog sfdisk lsblk)
 declare -A AsUser
 declare -i quiet=0 grafico=0 auto=0
@@ -713,8 +713,8 @@ sh_mount() {
 }
 
 sh_fluxboxminimal() {
-	local apkgs=(xorg-minimal xinit lxterminal fluxbox fbmenugen dejavu-fonts-ttf xterm
-					 pulseaudio vlc ristretto mupdf setxkbmap Thunar firefox firefox-i18n-pt-BR lxdm)
+	local apkgs=(xorg-minimal xinit lxterminal fluxbox fbmenugen dejavu-fonts-ttf xterm rxvt-unicode xfce4-terminal
+					 pulseaudio vlc ristretto mupdf setxkbmap Thunar pcmanfm firefox firefox-i18n-pt-BR lxdm)
 
 	sh_chroot_job "Instalando pacotes do fluxbox em $_PART_ROOT:$dir_install" "xbps-install -y ${apkgs[*]}"
 #	sh_chroot_job "Gerando menu customizado do fluxbox em $_PART_ROOT:$dir_install" "fbmenugen -i -o /home/${AsUser[cuser]}/.fluxbox/menu" "$err_not_fatal"
@@ -722,6 +722,13 @@ sh_fluxboxminimal() {
 		sed -e "/xmodmap/s//# xmodmap/" -i "$dir_install/home/${AsUser[cuser]}/.fluxbox/startup" > /dev/null 2>&1
  		sed -e '/\# xmodmap/a setxkbmap br -variant abnt2' -i "$dir_install/home/${AsUser[cuser]}/.fluxbox/startup"
 	fi
+}
+
+sh_openboxminimal() {
+	local apkgs=(xorg-minimal xinit lxterminal openbox dejavu-fonts-ttf xterm rxvt-unicode xfce4-terminal
+					 pulseaudio vlc ristretto mupdf setxkbmap Thunar pcmanfm firefox firefox-i18n-pt-BR lxdm)
+
+	sh_chroot_job "Instalando pacotes do openbox em $_PART_ROOT:$dir_install" "xbps-install -y ${apkgs[*]}"
 }
 
 sh_xorg(){
@@ -1035,6 +1042,7 @@ sh_confadduser()
          "Tam/Modelo: "                           7 1 "${SIZE_ORIGEM}/${MODEL_ORIGEM}" 7 28 20 0 2 \
          "FileSystem: "                           8 1 "${mkfs}"                        8 28 20 0 2 \
          "Teclado: "                              9 1 "${_KEYMAP}"                     9 28 20 0 2 \
+         "Window Manager: "                      10 1 "${wm}"                         10 28 20 0 2 \
          2>&1 1>&3)
          exit_status=$?
 
@@ -1173,27 +1181,37 @@ init() {
 	done
 }
 
-sh_choosegrub() {
-	local cefi='off'
-	local cbios='on'
+sh_bootefi() {
+	efivar --list > /dev/null 2>&1
+}
+
+sh_windowmanager() {
+	local ctty='on'
+	local cfluxbox='off'
+	local copenbox='off'
 	local cextra
 
-	if sh_bootefi ; then
-		cefi='on'
-		cbios='off'
-		cextra="Detectado boot via EFI \n↓ é recomendável instalar ↓"
-	fi
-
-	mbr=$(${DIALOG} --radiolist "Instalacao do GRUB:\n\n$cextra"   \
-		0 0 0                                                       \
-		EFI     "Interface de Firmaware Extensivel" $cefi           \
-		BIOS    "Sistema Básico de Entrada e Saída" $cbios          \
+	wm=$(${DIALOG} --radiolist "Gerenciador de janelas:\n\n$cextra"	\
+		0 0 0																				\
+		tty     	"Somente terminal, sem interface gráfica"	$ctty			\
+		fluxbox	"Fluxbox"											$cfluxbox	\
+		openbox	"Openbox" 											$copenbox	\
 		2>&1 >/dev/tty )
 
 	exit_status=$?
 	case $exit_status in
 		"$D_ESC"|"$D_CANCEL")
-		return 1
+			"$DIALOG" --clear --backtitle "$ccabec" --yesno "Deseja sair sem instalar?" 0 0
+			case $? in
+	      	"$D_OK")
+					die "Instalação abortada..."
+             	break
+	            ;;
+				"$D_CANCEL")
+					exit_status=99
+					continue
+					;;
+			esac
 		;;
 	esac
 }
@@ -1225,6 +1243,39 @@ sh_choosekeymap() {
 	return $nchoice
 }
 
+sh_choosefilesystem() {
+	local cbtrfs='off'
+	local cxfs='off'
+	local cext4='on'
+	local cextra
+	local exit_status
+
+	cextra="↓ é recomendável EXT4 ↓"
+	mkfs=$(${DIALOG} --radiolist "Escolha o filesystem\n\n$cextra" \
+		0 0 0                                                       \
+		EXT4     "Rápido e maduro"                   $cext4         \
+		BTRFS    "Novos recursos, que são novidades" $cbtrfs        \
+		XFS      "Alto desempenho"                   $cxfs          \
+		2>&1 >/dev/tty )
+
+	exit_status=$?
+	case $exit_status in
+		"$D_ESC"|"$D_CANCEL")
+	       "$DIALOG" --clear --backtitle "$ccabec" --yesno "Deseja sair sem instalar?" 0 0
+	         case $? in
+	            "$D_OK")
+	               die "Instalação abortada..."
+	               break
+	               ;;
+	            "$D_CANCEL")
+	               exit_status=99
+	               continue
+	               ;;
+	         esac
+		;;
+	esac
+}
+
 sh_install() {
 	local apkgs=(base-system xz lvm2 wireless_tools mkinitcpio mkinitcpio-udev nano grub efivar efibootmgr os-prober)
 
@@ -1236,6 +1287,7 @@ sh_install() {
 	if conf2 "*** KEYBOARD ***" "Current layout : $_KEYMAP" "\n\n$cmsgSetKeyboardLayout?"; then
 		sh_choosekeymap
    fi
+	sh_windowmanager
 	sh_confadduser "$@"
 
 	if ! sh_mkparted; then die "Erro"; fi
@@ -1275,7 +1327,10 @@ sh_install() {
 		sh_set_keymap
 		sh_update_bashrc
 		sh_update_wpa_suplicant
-		sh_fluxboxminimal
+		case "$wm" in
+			"fluxbox")	sh_fluxboxminimal;;
+			"openbox")	sh_openboxminimal;;
+		esac
 		sh_mkservice
 		sh_chroot_job "Certificando que todos pacotes estejam configurados corretamente em $_PART_ROOT:$dir_install" "xbps-reconfigure -fa"
 		sh_chroot_job "Removendo pacote bootstrap em $_PART_ROOT:$dir_install" "xbps-remove -y base-voidstrap" "$err_not_fatal"
@@ -1287,6 +1342,8 @@ sh_install() {
 	fi
 	sh_umountfs
 }
+
+
 
 sh_ambiente
 sh_ascii_lines
